In [1]:
import pandas as pd
import numpy as np

In [10]:
series = pd.Series([10,20,30,40,50],index=['a','b','c','d','e'],name='number')
series

a    10
b    20
c    30
d    40
e    50
Name: number, dtype: int64

In [11]:
print(series.values)
print(series.index)
print(series.dtype)
print(series.shape)
print(series.size)
print(series.name)

[10 20 30 40 50]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
int64
(5,)
5
number

In [14]:
# series indexing
print(series['a'])
print(series['c'])

print(series.iloc[0])

10
30
10

In [16]:
df = pd.DataFrame({
    'PassengerId': range(1, 11),
    'Survived': [0, 1, 1, 1, 0, 0, 0, 1, 1, 0],
    'Pclass': [3, 1, 3, 1, 3, 3, 1, 3, 2, 3],
    'Name': ['Smith, Mr. John', 'Johnson, Mrs. Mary', 'Williams, Miss Sarah',
                'Brown, Mr. James', 'Jones, Mr. Robert', 'Davis, Mrs. Emily',
                'Miller, Mr. David', 'Wilson, Miss Emma', 'Moore, Mrs. Lisa',
                'Taylor, Mr. Thomas'],
    'Sex': ['male', 'female', 'female', 'male', 'male', 'female', 
            'male', 'female', 'female', 'male'],
    'Age': [22, 38, 26, 35, 28, None, 54, 4, 58, 33],
    'SibSp': [1, 1, 0, 1, 0, 0, 0, 3, 0, 0],
    'Parch': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    'Ticket': ['A/5 21171', 'PC 17599', 'STON/O2', '113803', '373450',
                '330877', '17463', '349909', 'SC/Paris', '349249'],
    'Fare': [7.25, 71.28, 7.92, 53.10, 8.05, 8.46, 51.86, 21.07, 26.00, 7.89],
    'Cabin': [None, 'C85', None, 'C123', None, None, 'E46', None, 'B28', None],
    'Embarked': ['S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'C', 'S']
})

In [17]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Smith, Mr. John",male,22.0,1,0,A/5 21171,7.25,None,S
1,2,1,1,"Johnson, Mrs. Mary",female,38.0,1,0,PC 17599,71.28,C85,C
2,3,1,3,"Williams, Miss Sarah",female,26.0,0,0,STON/O2,7.92,None,S
3,4,1,1,"Brown, Mr. James",male,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Jones, Mr. Robert",male,28.0,0,0,373450,8.05,None,S
5,6,0,3,"Davis, Mrs. Emily",female,NaN,0,0,330877,8.46,None,Q
6,7,0,1,"Miller, Mr. David",male,54.0,0,0,17463,51.86,E46,S
7,8,1,3,"Wilson, Miss Emma",female,4.0,3,1,349909,21.07,None,S
8,9,1,2,"Moore, Mrs. Lisa",female,58.0,0,0,SC/Paris,26.00,B28,C
9,10,0,3,"Taylor, Mr. Thomas",male,33.0,0,0,349249,7.89,None,S

In [18]:
print(f"Mean Age: {df['Age'].mean():.2f}")

Mean Age: 33.11

In [22]:
missing = df.isnull().sum()
missing

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            1
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          6
Embarked       0
dtype: int64

In [28]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
df.set_index("Name")

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000